version: '3.8'

services:
  app:
    image: eventify-backend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: dev
    command: npm start
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: eventify
      MYSQL_USER: root
      MYSQL_PASSWORD: Password@123
